on:
  push:
    branches:
      - dev
      - staging
      - main

name: Build and push to ECR
env:
  AWS_DEFAULT_REGION: eu-west-2
  AWS_DEFAULT_OUTPUT: json
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  
jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@dev
    - name: Set deployment environment
      id: set_env
      run: |
        if [[ "${{ github.ref_name }}" == "dev" ]]; then
          echo "env_name=dev" >> $GITHUB_OUTPUT
        elif [[ "${{ github.ref_name }}" == "staging" ]]; then
          echo "env_name=staging" >> $GITHUB_OUTPUT
        else
          echo "env_name=prod" >> $GITHUB_OUTPUT
        fi

    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

    - name: Build and Push Docker image
      run: |
        IMAGE_TAG=${{ steps.set_env.outputs.env_name }}
        IMAGE_URI=AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flaskapp:$IMAGE_TAG
        docker build -t $IMAGE_URI ./app
        docker push $IMAGE_URI

   
