apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: myflask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 389595560555.dkr.ecr.eu-west-2.amazonaws.com/flaskapp1
        ports:
        - containerPort: 80
